name: Check Terraform Format
runs:
  using: "composite"
  steps:
    - name: Check Terraform Format
      shell: bash
      run: |
          export BRANCH_NAME=origin/${{ github.event.repository.default_branch }}
          ./scripts/githooks/check-terraform-format.sh
