name: Count lines of code in this repository
runs:
  using: "composite"
  steps:
    - name: Count lines of code in this repository
      shell: bash
      run: |
          export FORMAT=default
          ./scripts/cloc-repository.sh
