name: Check Markdown Format
runs:
  using: "composite"
  steps:
    - name: Check Markdown Format
      shell: bash
      run: |
          export BRANCH_NAME=origin/${{ github.event.repository.default_branch }}
          ./scripts/githooks/check-markdown-format.sh
