name: CI/CD Pipeline
permissions:
  contents: read
  security-events: write
  id-token: write
  actions: write

on:
  push:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  get-metadata:
    name: "Get Metadata"
    runs-on: ubuntu-latest
    outputs:
      build_datetime: ${{ steps.metadata.outputs.build_datetime }}
      build_timestamp: ${{ steps.metadata.outputs.build_timestamp }}
      build_epoch: ${{ steps.metadata.outputs.build_epoch }}
      terraform_version: ${{ steps.metadata.outputs.terraform_version }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - id: metadata
        name: Get Metadata
        uses: ./.github/actions/get-metadata

      - id: cloc
        name: Get Lines of Code
        uses: ./.github/actions/cloc-repository

  formatting-checks:
    needs: [get-metadata]
    runs-on: ubuntu-latest
    name: Formatting Checks
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Check File Format
        uses: ./.github/actions/check-file-format

      - name: Check Markdown Format
        uses: ./.github/actions/check-markdown-format

      - name: Check Terraform Format
        uses: ./.github/actions/check-terraform-format

  security-scan:
    needs: [get-metadata]
    runs-on: ubuntu-latest
    name: Security Scanning
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Scan Dependencies
        uses: ./.github/actions/scan-dependencies

      - name: Scan Secrets
        uses: ./.github/actions/scan-secrets


  checkov:
    name: Checkov
    runs-on: ubuntu-latest
    needs: [formatting-checks, security-scan]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.11'

      - name: Install Latest Checkov
        id: install-checkov
        run: pip install --user checkov

      - name: Run Checkov
        id: run-checkov
        run: checkov --directory . -o sarif -s --quiet

      - name: Upload SARIF File
        uses: github/codeql-action/upload-sarif@1c5b675653bb5c22dbe9b12b556ec555138e09fd # v4.38.1
        if: always() && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        with:
          sarif_file: results.sarif

  tflint:
    name: TFLint
    runs-on: ubuntu-latest
    needs: [formatting-checks, security-scan]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup TFLint Cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@1cf010d3c7aef302051ccdb68c14c5dc2efa34ef # v6.3.1
        with:
          tflint_version: v0.47.0

      - name: Init TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint -f compact

  build-example-app:
    name: Build Example App
    runs-on: ubuntu-latest
    needs: [tflint, checkov]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4.0.1

      - name: Install Example Dependencies
        run: make example-install

      - name: Build Example App
        run: make example-build

      - name: Zip OpenNext Deployment Assets
        run: cd example/.open-next && zip -r ../../open-next.zip . -q

      - name: Store Build Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: example-app-opennext-build
          path: open-next.zip

  deploy:
    name: Deploy Example App
    runs-on: ubuntu-latest
    needs: [build-example-app]
    if: success() && github.ref_name == 'main'
    concurrency: example-deploy
    environment:
      name: Example Application
      url: https://terraform-aws-opennext.tools.engineering.england.nhs.uk/

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4.0.1

      - id: aws-credentials
        name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6.3.0
        with:
          role-to-assume: ${{ secrets.DEPLOYMENT_IAM_ROLE }}
          aws-region: eu-west-2

      - name: Get Current Identity
        run: aws sts get-caller-identity

      - name: Download Build Artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: example-app-opennext-build

      - name: Unzip Build Artifacts to .open-next folder
        run: unzip -q -d example/.open-next open-next.zip

      - name: Run Terraform Init
        run: terraform -chdir=example/terraform init

      - name: Run Terraform Plan
        run: terraform -chdir=example/terraform plan -out example-app.tfplan

      - name: Store Terraform Plan Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: example-app-tfplan-output
          path: example/terraform/example-app.tfplan

      - name: Run Terraform Apply
        run: terraform -chdir=example/terraform apply example-app.tfplan

      - name: Get CloudFront Distribution ID
        id: get_distribution_id
        run: echo "distribution_id=$(terraform -chdir=example/terraform output -raw cloudfront_distribution_id)" >> "$GITHUB_OUTPUT"

      - name: Trigger CloudFront Cache Invalidation
        id: trigger_invalidation
        run: echo "invalidation_id=$(aws cloudfront create-invalidation --distribution-id ${{ steps.get_distribution_id.outputs.distribution_id }} --paths '/*' --output text --query Invalidation.Id)" >> "$GITHUB_OUTPUT"

      - name: Wait for Invalidation
        run: aws cloudfront wait invalidation-completed --distribution-id ${{ steps.get_distribution_id.outputs.distribution_id }} --id ${{ steps.trigger_invalidation.outputs.invalidation_id }}
